version: '3.7'
services:
  rosetta-cli:
    build:
      context: ../rosetta-cli-config
      dockerfile: docker/Dockerfile
    command: ${CMD}
    volumes:
      - ${OUTPUT}
    extra_hosts:
      - "host.docker.internal:host-gateway" # fixes `host.docker.internal` on linux hosts
