name: Build on master push

on:
  push:
    branches:
      - master

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout project
        uses: actions/checkout@v2

      - id: keydb
        uses: oz-elhassid/get-latest-release@master
        with:
          repository: hirosystems/stacks-blockchain-api
          excludes: prerelease, draft

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Show available Docker buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Docker buildx for Alpine
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file .github/workflows/dockerfiles/Dockerfile.hub \
          --build-arg GIT_TAG=${{ steps.keydb.outputs.tag_name }} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/stacks-blockchain-api:${{ steps.keydb.outputs.tag_name }} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/stacks-blockchain-api:latest \
          --push .

